### ISSUE TITLE
service not running

### ISSUE THREAD

**Issue by OfficialKaos** [hoobs-org/hoobs-upgrade#1] opened 2019-11-15 21:38 UTC
homebridge service not running after upgrade no username or pin issued

**Comment by mkellsy** [comment] 2019-11-16 03:07
Are you running this on a Raspberry Pi or a different device?
What OS are you running?
Please elaborate on "no username or pin issued", are you getting from the log?
I am trying to reproduce but I don't have enough info.

**Comment by askovi** [comment] 2019-11-16 03:14
I had the same report from another user. After upgrading from v2 to v3 using the upgrade plugin, there was no username and pin in settings and clicking on 'saved changes' button would error out saying 
`Unable to save.
Please fix the following errors.

Service name is required.
Service port is invalid. It must be a number between 1 and 65535.
Home username is required.
Home PIN is required`

**Comment by OfficialKaos** [comment] 2019-11-16 06:55
Yes ... This is exactly what is happening

**Comment by mkellsy** [comment] 2019-11-16 14:17
I think it is caused by n not finding Node for ARM. I am looking into a different way to install Node LTS.

I am closing this task it is the same cause as issue #244 in the main public repo.

**Closed by mkellsy** 2019-11-16 14:17 UTC
